#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/bash

export SCRAM_ARCH=slc6_amd64_gcc481
cd /afs/cern.ch/user/k/ktos/NMSSM_Analysis/CMSSW_7_4_12_patch4/src/
eval `scramv1 runtime -sh`
cd -
source /afs/cern.ch/cms/caf/setup.sh
cp /afs/cern.ch/user/k/ktos/NMSSM_Analysis/CMSSW_7_4_12_patch4/src/BBA/Analyzer/BSUB/BBATauReco_a30_muchMore_DEC_15_v2/bbaTauRecoAnalyzer_cfg_BBATauReco_a30_muchMore_DEC_15_v2.py .
cmsRun bbaTauRecoAnalyzer_cfg_BBATauReco_a30_muchMore_DEC_15_v2.py
rm bbaTauRecoAnalyzer_cfg_BBATauReco_a30_muchMore_DEC_15_v2.py 
exit 0

_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
